
name: financeiro

services:
  backend:
    container_name: financeiro_backend
    build:
      context: ./financeiro-backend
      dockerfile: Dockerfile # <-- CORREÇÃO: Remova o caminho da pasta aqui
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./financeiro_data:/app
    networks:
      - financeiro_network

  frontend:
    container_name: financeiro_frontend
    build:
      context: ./financeiro-frontend
      dockerfile: Dockerfile # <-- CORREÇÃO: Remova o caminho da pasta aqui
      args:
        NEXT_PUBLIC_API_URL: /financeiro/api 
    restart: unless-stopped
    ports:
      - "3002:3000"
    depends_on:
      - backend
    networks:
      - financeiro_network

networks:
  financeiro_network:
    driver: bridge